model_train_type = "sdxl-lora"
pretrained_model_name_or_path = "./sd-models/model.safetensors"
train_data_dir = "./train/aki"
prior_loss_weight = 1
resolution = "1024,1024"
enable_bucket = true
min_bucket_reso = 512
max_bucket_reso = 2048
bucket_reso_steps = 64
bucket_no_upscale = true
output_name = "jianmo"
output_dir = "./output"
save_model_as = "safetensors"
save_precision = "bf16"
save_every_n_epochs = 1
save_state = false
max_train_epochs = 30
train_batch_size = 8
gradient_checkpointing = true
gradient_accumulation_steps = 2
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 1
unet_lr = 1
text_encoder_lr = 1
lr_scheduler = "constant"
lr_warmup_steps = 0
optimizer_type = "Prodigy"
network_module = "lycoris.kohya"
network_dim = 100000
network_alpha = 1
scale_weight_norms = 1
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = false
keep_tokens = 0
max_token_length = 255
flip_aug = true
seed = 1337
mixed_precision = "bf16"
xformers = true
sdpa = false
lowram = false
cache_latents = true
cache_latents_to_disk = true
persistent_data_loader_workers = true
save_last_n_epochs_state = 1
network_args = [ "conv_dim=4", "conv_alpha=1", "dropout=0", "algo=loha" ]
optimizer_args = [
  "decouple=True",
  "weight_decay=0.01",
  "use_bias_correction=True",
  "d_coef=2.0"
]
